import { describe, expect, it } from 'vitest';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import rawRoutingConfig from '../../../config/openrouter-routing.json';
import rawTaskDefaults from '../../../config/task-defaults.json';
import { THINKING_TASKS } from '../../../src/lib/thinking-defaults';
import {
  OpenRouterRoutingConfigSchema,
  openRouterProviderRoutingForModel,
} from '../openrouter-provider-routing';

describe('openRouterProviderRoutingForModel', () => {
  it('round-trips config/openrouter-routing.json through the schema', () => {
    expect(OpenRouterRoutingConfigSchema.safeParse(rawRoutingConfig).success).toBe(true);
  });

  it('returns no routing override for a model with no entry', () => {
    // The mechanism's contract: an unknown model means "let OpenRouter decide",
    // not "fail" and not "apply someone else's pin".
    expect(openRouterProviderRoutingForModel('deepseek/deepseek-v4.1-flash')).toEqual({});
    expect(openRouterProviderRoutingForModel('some/other-model')).toEqual({});
  });

  it('emits a provider block for a configured model', () => {
    // Exercised against whatever the shipped config contains, so this keeps
    // testing the mapping even while the config is empty.
    const entry = Object.keys(rawRoutingConfig.modelProviderRouting)[0];
    if (!entry) {
      expect(openRouterProviderRoutingForModel('anything')).toEqual({});
      return;
    }
    const routed = openRouterProviderRoutingForModel(entry);
    expect(routed.provider?.order.length).toBeGreaterThan(0);
    expect(typeof routed.provider?.allow_fallbacks).toBe('boolean');
  });

  it('carries no routing entry for a model nothing selects any more', () => {
    /**
     * Regression guard for a stale-config trap. `minimax/minimax-m2.5` kept a
     * `{ order: ['mara'], allow_fallbacks: false }` pin long after the default
     * moved to `deepseek/deepseek-v4.1-flash`. Nothing consumed it, but it made
     * the repo read as though it were still configured for MiniMax — which is
     * how it looked while debugging the model label on the preview card.
     *
     * A routing entry should exist only for a model something actually selects.
     */
    const configured = Object.keys(rawRoutingConfig.modelProviderRouting);
    const defaults: string[] = THINKING_TASKS.map(
      (task) => rawTaskDefaults.perTaskDefaults[task]?.modelId,
    );
    const stale = configured.filter((modelId) => !defaults.includes(modelId));
    expect(stale, `stale routing entries: ${stale.join(', ')}`).toEqual([]);
  });
});

describe('committed API function bundle', () => {
  /**
   * The generated bundle is committed to the repo, so it can silently disagree
   * with the source it is built from. That happened: `config/openrouter-routing.json`
   * dropped its `minimax/minimax-m2.5` entry, but `api/[[...route]].js` kept
   * `const modelProviderRouting = { "minimax/minimax-m2.5": {...} }` until the
   * bundle was regenerated by hand.
   *
   * `vercel.json` rebuilds it on every deploy, so it never affected production —
   * but it made the repo read as though it were still configured for a model
   * nothing selects, which is exactly what it looked like when investigating a
   * preview card showing `minimax/minimax-m2.5`.
   *
   * This checks the bundle embeds no model the config no longer knows about.
   */
  it('does not embed a model that has been dropped from every default', () => {
    const bundle = readFileSync(resolve(__dirname, '../../../api/[[...route]].js'), 'utf8');
    const configured = Object.keys(rawRoutingConfig.modelProviderRouting);
    // Any model id that appears in the bundle as a routing key must still be a
    // configured default; otherwise it is a leftover from an earlier build.
    const routingKeys = [...bundle.matchAll(/modelProviderRouting = \{([^}]*)\}/g)].flatMap((m) =>
      [...m[1].matchAll(/"([^"]+)":/g)].map((k) => k[1]),
    );
    const defaults: string[] = THINKING_TASKS.map(
      (task) => rawTaskDefaults.perTaskDefaults[task]?.modelId,
    );
    const stale = routingKeys.filter((id) => !configured.includes(id) && !defaults.includes(id));
    expect(stale, `stale routing keys in api/[[...route]].js: ${stale.join(', ')}`).toEqual([]);
  });
});
